#!/system/bin/sh

BASEBAND_SWITCH_PROP="persist.sys.new_baseband"
BASEBAND_SWITCH_PROP_FILE="/data/property/$BASEBAND_SWITCH_PROP"
BASEBAND_FILES_BASE="/system/etc/motorola/basebands"
BASEBAND_DEFAULT="/system/etc/motorola/bp_nvm_default"
BASEBAND_DATA_DIR="/data/bp_nvm"
PDS_BACKUP_FILE="/data/pdsdata.img"


if [ -e $BASEBAND_SWITCH_PROP_FILE ]; then
    NEW_BASEBAND=`cat $BASEBAND_SWITCH_PROP_FILE`
    NEW_BASEBAND_ZIP="$BASEBAND_FILES_BASE/$NEW_BASEBAND.zip"

    setprop $BASEBAND_SWITCH_PROP ""
    rm -f $BASEBAND_SWITCH_PROP_FILE

    if [ -f $NEW_BASEBAND_ZIP ]; then
        mount -o remount,rw /system
        rm -f $BASEBAND_DEFAULT/*
        unzip -q $NEW_BASEBAND_ZIP -d $BASEBAND_DEFAULT
        mount -o remount,ro /system
        rm -f $BASEBAND_DATA_DIR/*
        rm -f $PDS_BACKUP_FILE
        reboot
    fi
fi

